/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2021-03-01 15:26:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.*;
import bean.*;

public final class notice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("dao");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("bean");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	/*------------------------------------------------------------------------------------------------
	修改人：王旭升		     
	修改时间 ：2021-1-9	
	修改内容：增加后台
	版本号			 
	-------------------------------------------------------------------------------------------------*/

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"Css/Public_Color/orange.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"Css/Public_style.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"Css/Homepage.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    ");

      String ID = null;
 	  if (request.getAttribute("ID") != null || request.getAttribute("ID") != "") {//获取Homepage.jsp页面中传过来的ID
		ID=request.getParameter("ID");
	}
      notice_bean not=new notice_bean();
      String[] cont = not.content();
      String[] sid = not.sid();
      for(int x=0;x<9;x++){
    	  System.out.println("..."); 
    	  System.out.println(sid[x]); 
      }
    
      out.write("\r\n");
      out.write("\t<ul class=\"notice_whole_ul dinylight-color\">\r\n");
      out.write("        ");

         for(int i=0;i<9;i++){
        	  if(i%2==0){
        		  
      out.write("\r\n");
      out.write("        \t\t  <form action=\"notice_detail\" method=\"post\" id=\"form_");
      out.print(i);
      out.write("\">\r\n");
      out.write("        \t\t  \t<input type=\"text\" name=\"ID\" value=\"");
      out.print(ID);
      out.write("\" style=\"display:none\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"notice_ID\" value=\"");
      out.print(sid[i]);
      out.write("\" style=\"display:none\"/>\r\n");
      out.write("                  <li class=\"small-font\"style=\"cursor:pointer;\"><a onclick=\"document:form_");
      out.print(i);
      out.write(".submit();\" >");
      out.print(cont[i]);
      out.write("</a></li>\t\r\n");
      out.write("                  </form>\r\n");
      out.write("        \t      ");

        	  }else if(i%2==1){
        		  
      out.write("\r\n");
      out.write("        \t\t  <form action=\"notice_detail\" method=\"post\" id=\"form_");
      out.print(i);
      out.write("\">\r\n");
      out.write("        \t\t  \t<input type=\"text\" name=\"ID\" value=\"");
      out.print(ID);
      out.write("\" style=\"display:none\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"notice_ID\" value=\"");
      out.print(sid[i]);
      out.write("\" style=\"display:none\"/>\r\n");
      out.write("                  <li class=\"small-font\" style=\"background-color: white;cursor:pointer;\">\r\n");
      out.write("                  \t<a onclick=\"document:form_");
      out.print(i);
      out.write(".submit();\">");
      out.print(cont[i]);
      out.write("</a>\r\n");
      out.write("                  </li>\t\r\n");
      out.write("                  </form>\r\n");
      out.write("        \t\t  ");

        	}
          }        
        
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<li class=\"small-font\" style=\"background-color: white;\">\r\n");
      out.write("\t\t<div id=\"submit\" style=\"border:1px soild #FAFAFA\">\r\n");
      out.write("\t\t\t\t<form action=\"notice_all\" method=\"post\" id=\"form_all\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"ID\" value=\"");
      out.print(ID);
      out.write("\" style=\"display:none\"/>\r\n");
      out.write("\t\t\t\t<a id=\"url\" onclick=\"document:form_all.submit();\"style=\"cursor:pointer;\"><font class=\"small-font-B font-normal-color\">查看全部</font></a>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</li>\t\r\n");
      out.write("\t</ul>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
