/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2021-03-01 14:34:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.NoticeAll_Dao;
import bean.Homepage_bean;
import java.util.StringTokenizer;

public final class notice_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bean.Homepage_bean");
    _jspx_imports_classes.add("java.util.StringTokenizer");
    _jspx_imports_classes.add("dao.NoticeAll_Dao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"Css/Public_Color/orange.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"Css/Public_style.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"Css/Homepage.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("\t\tbutton{\r\n");
      out.write("\t\t\tborder:0;\r\n");
      out.write("\t\t\toutline:none;\r\n");
      out.write("\t\t\tcursor:pointer;\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body bgcolor=\"#F4F5F7\">\r\n");
      out.write("\t");

	request.setCharacterEncoding("UTF-8") ;//或者指定的编码(GBK或其他)
	String ID = null;
	String notice_ID = "1";
	if (request.getAttribute("notice_ID") != null || request.getAttribute("notice_ID") != "") {
		notice_ID=request.getParameter("notice_ID");
	}
	if (request.getAttribute("ID") != null || request.getAttribute("ID") != "") {
		ID=request.getParameter("ID");
	}
	System.out.println(ID+"---公告详情传来的用户id");
	System.out.println(notice_ID+"----公告详情传来的详情id");
	
	NoticeAll_Dao tp = new NoticeAll_Dao();
	Homepage_bean bean = new Homepage_bean(ID);
	bean.head();
	String text_line = tp.get_content(notice_ID);
	StringTokenizer line_cut = new StringTokenizer(text_line,"麤讜黌");
	
	String posterer_id = line_cut.nextToken();//创建变量存储 id
	String poster_nickiname = tp.get_nickiname(posterer_id);//根据id 获取昵称
	String poster_headPhoto =tp.get_headPhoto(posterer_id);//根据id 获取头像		
	
	String tittle = line_cut.nextToken();
	String content = line_cut.nextToken();
	String date = line_cut.nextToken();
	
	String allmess = tp.get_Tittle();
	System.out.println(allmess);
	StringTokenizer line_cut2 = new StringTokenizer(allmess,"麤讜黌");
	
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 调用头部页面 -->\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "season.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("level", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(bean.level ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("nickiname", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(bean.nickiname ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("sign", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(bean.sign ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("background", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(bean.background ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("headphoto", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(bean.headphoto ), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "lead.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("ID", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(ID ), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"width:75%;margin:0 auto;\">\r\n");
      out.write("\t\t<div class=\"small-tittle middle-font font-normal-color\">\r\n");
      out.write("\t\t\t\t<div style=\"background-color: #FAFAFA;float:left;\"  >&nbsp;┃&nbsp;</div>\r\n");
      out.write("\t\t\t\t<div style=\"background-color: #FAFAFA;float:left; width:60%\"  >\r\n");
      out.write("\t\t\t\t<form action=\"Homepage.jsp\" method=\"post\" name=\"\">\r\n");
      out.write("\t\t\t\t<button class=\"middle-font font-light-color\" value=\"");
      out.print(ID);
      out.write("\" name=\"ID\" style=\"background-color: #FAFAFA;float:left;\" >主页 </button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form action=\"notice_all\" method=\"post\" name=\"\">\r\n");
      out.write("\t\t\t\t<button class=\"middle-font font-light-color\" value=\"");
      out.print(ID);
      out.write("\" name=\"ID\" style=\"background-color: #FAFAFA;float:left;margin-left:4px;\" >   / 全部公告  </button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<button class=\"middle-font font-light-color\" value=\"");
      out.print(ID);
      out.write("\" name=\"ID\" disabled=\"disabled\" style=\"background-color: #FAFAFA;float:left;margin-left:4px;\" > / ");
      out.print(tittle );
      out.write("</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"background-color: #FAFAFA;float:right; width:35%\"  >\r\n");
      out.write("\t\t\t\t<img  src=\"img/lead_photo/返回.png\"style=\"width:30px;height:25px;float:right;\">\r\n");
      out.write("\t\t\t\t<form action=\"notice_all\" method=\"post\" name=\"\">\r\n");
      out.write("\t\t\t\t<button class=\"middle-font font-light-color\" value=\"");
      out.print(ID);
      out.write("\" name=\"ID\" style=\"float:right;background-color: #FAFAFA\" >返回上一级</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"width:100%;height:685px;padding-top:15px;\" class=\"dinylight-color\">\t\r\n");
      out.write("\t\t<div style=\"margin-left:1%;width:23%;height:650px;float:left;margin-top:6px;\">\r\n");
      out.write("\t\t<div class=\"small-tittle middle-font font-normal-color\">&nbsp;┃&nbsp;<a class=\"middle-font font-normal-color\">全部公告</a></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<div style=\"width:100%;height: 615px; color: darkslategray;overflow-y:auto;\">\r\n");
      out.write("\t\t\t\t");

				   int i = 0;
				   String allnotice_id = null;
					while(line_cut2.hasMoreTokens()){
						allnotice_id = line_cut2.nextToken();
						if(i%2!=0){
							if(!allnotice_id.equals(notice_ID)){
							out.println("<form action=\"notice_detail.jsp\" method=\"post\"><input type=\"text\" style=\"display:none;\" value=\""+ID+"\" name=\"ID\"><input type=\"text\" style=\"display:none;\" value=\""+allnotice_id+"\" name=\"notice_ID\"><button style=\"width:100%;height: 35px;margin-top:6px;line-height:35px;\" class=\"dinylight-color\">&nbsp;"+line_cut2.nextToken()+"</button></form>");
							}
							if(allnotice_id.equals(notice_ID)){
							out.println("<div style=\"width:100%;height: 35px;text-align:center;margin-top:6px;line-height:35px;\" class=\"dinylight-color font-normal-color\">&nbsp;"+line_cut2.nextToken()+"</div>");
							}
						}	
						if(i%2==0){
							if(!allnotice_id.equals(notice_ID)){
							 out.println("<form action=\"notice_detail.jsp\" method=\"post\"><input type=\"text\" style=\"display:none;\" value=\""+ID+"\" name=\"ID\"><input type=\"text\" style=\"display:none;\" value=\""+allnotice_id+"\" name=\"notice_ID\"><button style=\"width:100%;height: 35px;margin-top:6px;background-color: white;line-height:35px;\">&nbsp;"+line_cut2.nextToken()+"</button></form>");
							}	
							if(allnotice_id.equals(notice_ID)){
								out.println("<div style=\"width:100%;height: 35px;background-color: white;text-align:center;margin-top:6px;line-height:35px;\" class=\"font-normal-color\">&nbsp;"+line_cut2.nextToken()+"</div>");
							}
						}
						i++;
					}
				
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div style=\"margin-left:1%;margin-top:6px;width:5%;height:652px;background-color:white;float:left;border-radius:10px 0px 0px 10px;\">\r\n");
      out.write("\t\t\t\t<div style=\"width:100%;height:5px;margin-top:45px;\"class=\"light-color\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"width:100%;height:5px;margin-top:45px;\"class=\"light-color\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"width:100%;height:5px;margin-top:45px;\"class=\"light-color\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"width:100%;height:5px;margin-top:45px;\"class=\"light-color\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"width:100%;height:5px;margin-top:45px;\"class=\"light-color\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"width:100%;height:5px;margin-top:45px;\"class=\"light-color\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"width:100%;height:5px;margin-top:45px;\"class=\"light-color\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"width:100%;height:5px;margin-top:45px;\"class=\"light-color\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"width:100%;height:5px;margin-top:45px;\"class=\"light-color\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"width:100%;height:5px;margin-top:45px;\"class=\"light-color\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"width:100%;height:5px;margin-top:45px;\"class=\"light-color\"></div>\r\n");
      out.write("\t\t\t\t<div style=\"width:100%;height:5px;margin-top:45px;\"class=\"light-color\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div style=\"float:left;width:69.5%;margin-left:0.5%;height:637px;padding-top:15px;margin-top:6px;background-color:white;border-radius:0px 10px 10px 0px;\">\r\n");
      out.write("\t\t\t\t<div style=\"width:75%;height:30px;margin:0 auto;border-badius:3px;line-height:30px;\"class=\"light-color\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<font style=\"color:white;float:left;\">&nbsp;&nbsp;┃</font>\t\r\n");
      out.write("\t\t\t\t\t");
      out.print(tittle );
      out.write("\r\n");
      out.write("\t\t\t\t\t<font style=\"color:white;float:right;\">┃&nbsp;&nbsp;</font>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"width:75%;height:450px;margin:0 auto;\"><br/>\r\n");
      out.write("\t\t\t\t<textarea style=\"line-height:25px; width:100%;height:400px;border:0px solid white\" readonly>");
      out.print(content);
      out.write("\r\n");
      out.write("\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"width:15%;height:130px;float:right;margin-right:12.5%;\" align=\"center\">\r\n");
      out.write("\t\t\t\t<img  src=\"img/head_photo/");
      out.print(poster_headPhoto);
      out.write(".jpg\"style=\"width:50px;height:50px;border-radius:25px;\"><br/>\r\n");
      out.write("\t\t\t\t<font color=\"gray\">");
      out.print(poster_nickiname );
      out.write("</font><br/><br/>\r\n");
      out.write("\t\t\t\t\t<font color=\"gray\">");
      out.print(date );
      out.write("</font>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-3.4.1.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$('#homepage').css('border-bottom-style','solid');\r\n");
      out.write("\tvar $logo = $('#sign_list li');\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t $logo.mouseenter(function(){\r\n");
      out.write("    \t $(this).css('border-bottom-style','solid');\r\n");
      out.write("    \t $('#homepage').css('border-bottom-style','none');\r\n");
      out.write(" \t\t});\r\n");
      out.write("\t \r\n");
      out.write("\t $logo.mouseleave(function(){ \r\n");
      out.write("\t\t  $logo.css('border-bottom-style','none');\r\n");
      out.write("\t\t  $('#homepage').css('border-bottom-style','solid');\r\n");
      out.write("\t\t });\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
