/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2021-02-24 14:02:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bean.question_bean;

public final class question_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bean.question_bean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

/*------------------------------------------------------------------------------------------------
修改人			     
修改时间 		
修改内容		
版本号			 
-------------------------------------------------------------------------------------------------*/
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./Css/question.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./Css/Public_style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"./Css/Public_Color/orange.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body  bgcolor=\"#F4F5F7\">");

	request.setCharacterEncoding("UTF-8") ;//或者指定的编码(GBK或其他)
String ID=(String)request.getAttribute("ID"); 
question_bean bean=new question_bean(ID);
bean.head();
String role=bean.role;

      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "season.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("level", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(bean.level ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("role", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(role ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("nickiname", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(bean.nickiname ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("sign", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(bean.sign ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("background", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(bean.background ), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("headphoto", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(bean.headphoto ), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "lead.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("ID", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(ID ), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\t<div class=\"top_background\">\r\n");
      out.write("\t\t<div class=\"ask_box_left light-color\"></div>\r\n");
      out.write("\t<div class=\"ask_box\">\r\n");
      out.write("\t\t<div class=\"ask_box_txtline middle-font font-normal-color\">#有什么想分享给大家的吗&nbsp;?</div>\r\n");
      out.write("\t\t<div class=\"ask_box_symline middle-font font-normal-color\" id=\"ask_sym\">提问▼</div>\r\n");
      out.write("\t\t<div class=\"ask_box_symline middle-font font-normal-color\" id=\"answer_sym\">收起▲</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"ask_background\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 页面头部 -->\r\n");
      out.write("\t\t<div class=\"chose_type\">\r\n");
      out.write("\t\t\t<button class=\"type_type middle-font light-color cilck_style\">关于学习</button>\r\n");
      out.write("\t\t\t<button class=\"type_type middle-font dinylight-color uncilck_style\">关于协会</button>\r\n");
      out.write("\t\t\t<button class=\"type_type middle-font dinylight-color uncilck_style\">关于网站</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<textarea class=\"textarea middle-font\"></textarea>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"sub\">\r\n");
      out.write("\t\t<button type=\"submit\" class=\"submit_button middle-font light-color\">提交反馈</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"asktype_head\">\r\n");
      out.write("\t\t<div class=\"asktype_allquestion light-color cilck_style\" id=\"all_question\">看看大家的问题</div>\r\n");
      out.write("\t\t<div class=\"asktype_myquestion font-normal-color\" id=\"my_question\">查看我提出的问题</div>\r\n");
      out.write("\t\t<!-- 搜索 -->\r\n");
      out.write("\t\t\t<div class=\"asktype_search\">\r\n");
      out.write("\t\t\t\t<div class=\"search_area\">\r\n");
      out.write("\t\t\t\t\t<div class=\"search \">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"search-block\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"search-symble\" style=\"margin-left: 4%;\"><img src=\"img/lead_photo/搜索.png\" style=\"width: 90%; height:90%;\"/></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"search-form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" style=\"width: 73.5%;height: 25px;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"check_button normal-color\" value=\"搜索\" />\r\n");
      out.write("\t\t\t\t\t\t\t       </form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<div class=\"type_choose_area\">\r\n");
      out.write("\t\t\t\t<div class=\"type_choose_line small-font underline_show\" id=\"about_study\">关于学习</div>\r\n");
      out.write("\t\t\t\t<div class=\"type_choose_row font-normal-color\">|</div>\r\n");
      out.write("\t\t\t\t<div class=\"type_choose_line small-font underline_hide\" id=\"about_pca\">关于协会</div>\r\n");
      out.write("\t\t\t\t<div class=\"type_choose_row font-normal-color\">|</div>\r\n");
      out.write("\t\t\t\t<div class=\"type_choose_line small-font underline_hide\" id=\"about_website\">关于网站</div>\r\n");
      out.write("\t\t\t\t<div class=\"type_choose_row font-normal-color\">|</div>\r\n");
      out.write("\t\t\t\t<div class=\"type_choose_line small-font underline_hide\" id=\"about_all\">查看全部</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"all_question\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "all_question.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$('#question').css('border-bottom-style','solid');\r\n");
      out.write("\tvar $logo = $('#sign_list li');\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t $logo.mouseenter(function(){\r\n");
      out.write("    \t $(this).css('border-bottom-style','solid');\r\n");
      out.write("    \t $('#question').css('border-bottom-style','none');\r\n");
      out.write(" \t\t});\r\n");
      out.write("\t \r\n");
      out.write("\t $logo.mouseleave(function(){ \r\n");
      out.write("\t\t  $logo.css('border-bottom-style','none');\r\n");
      out.write("\t\t  $('#question').css('border-bottom-style','solid');\r\n");
      out.write("\t\t });\r\n");
      out.write("\t});\r\n");
      out.write("$(function() {\r\n");
      out.write("\t\r\n");
      out.write("\t//提问区域隐藏\r\n");
      out.write("\t$('.ask_background').hide();\r\n");
      out.write("\t$('#sub').hide();\r\n");
      out.write("\t$('#answer_sym').hide();\r\n");
      out.write("\r\n");
      out.write("\t$(\"#ask_sym\").click(function() {\r\n");
      out.write("\t\t$('.ask_background').show();\r\n");
      out.write("\t\t$('#sub').show();\r\n");
      out.write("\t\t$('#ask_sym').hide();\r\n");
      out.write("\t\t$('#answer_sym').show();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#answer_sym\").click(function() {\r\n");
      out.write("\t\t$('.ask_background').hide();\r\n");
      out.write("\t\t$('#sub').hide();\r\n");
      out.write("\t\t$('#answer_sym').hide();\r\n");
      out.write("\t\t$('#ask_sym').show();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//选择特效与跳转\r\n");
      out.write("\t$('#my_question')\r\n");
      out.write("\t.click(\r\n");
      out.write("\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t$(this).removeClass(\"font-normal-color\");\r\n");
      out.write("\t\t\t\t$(this).addClass(\"light-color cilck_style\");\r\n");
      out.write("\t\t\t\t$('#all_question').removeClass(\"light-color cilck_style\");\r\n");
      out.write("\t\t\t\t$('#all_question').addClass(\"font-normal-color\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t$('#all_question')\r\n");
      out.write("\t.click(\r\n");
      out.write("\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t$(this).removeClass(\"font-normal-color\");\r\n");
      out.write("\t\t\t\t$(this).addClass(\"light-color cilck_style\");\r\n");
      out.write("\t\t\t\t$('#my_question').removeClass(\"light-color cilck_style\");\r\n");
      out.write("\t\t\t\t$('#my_question').addClass(\"font-normal-color\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//分支特效\r\n");
      out.write("\r\n");
      out.write("\t$('#about_study').click(\r\n");
      out.write("\t\tfunction() {\r\n");
      out.write("\t\t\t$(this).removeClass(\"underline_hide\");\r\n");
      out.write("\t\t\t$(this).addClass(\"underline_show\");\t\r\n");
      out.write("\t\t\tif ($('#about_pca').hasClass('underline_show')) {\r\n");
      out.write("\t\t\t\t$('#about_pca').removeClass('underline_show');\r\n");
      out.write("\t\t\t\t$('#about_pca').addClass('underline_hide');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif ($('#about_all').hasClass('underline_show')) {\r\n");
      out.write("\t\t\t\t$('#about_all').removeClass('underline_show');\r\n");
      out.write("\t\t\t\t$('#about_all').addClass('underline_hide');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif ($('#about_website').hasClass('underline_show')) {\r\n");
      out.write("\t\t\t\t$('#about_website').removeClass('underline_show');\r\n");
      out.write("\t\t\t\t$('#about_website').addClass('underline_hide');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t$('#about_pca').click(\r\n");
      out.write("\t\tfunction() {\r\n");
      out.write("\t\t\t$(this).removeClass(\"underline_hide\");\r\n");
      out.write("\t\t\t$(this).addClass(\"underline_show\");\t\r\n");
      out.write("\t\t\tif ($('#about_study').hasClass('underline_show')) {\r\n");
      out.write("\t\t\t\t$('#about_study').removeClass('underline_show');\r\n");
      out.write("\t\t\t\t$('#about_study').addClass('underline_hide');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif ($('#about_all').hasClass('underline_show')) {\r\n");
      out.write("\t\t\t\t$('#about_all').removeClass('underline_show');\r\n");
      out.write("\t\t\t\t$('#about_all').addClass('underline_hide');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif ($('#about_website').hasClass('underline_show')) {\r\n");
      out.write("\t\t\t\t$('#about_website').removeClass('underline_show');\r\n");
      out.write("\t\t\t\t$('#about_website').addClass('underline_hide');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t\r\n");
      out.write("\t$('#about_website').click(\r\n");
      out.write("\t\tfunction() {\r\n");
      out.write("\t\t\t$(this).removeClass(\"underline_hide\");\r\n");
      out.write("\t\t\t$(this).addClass(\"underline_show\");\t\r\n");
      out.write("\t\t\tif ($('#about_study').hasClass('underline_show')) {\r\n");
      out.write("\t\t\t\t$('#about_study').removeClass('underline_show');\r\n");
      out.write("\t\t\t\t$('#about_study').addClass('underline_hide');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif ($('#about_all').hasClass('underline_show')) {\r\n");
      out.write("\t\t\t\t$('#about_all').removeClass('underline_show');\r\n");
      out.write("\t\t\t\t$('#about_all').addClass('underline_hide');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif ($('#about_pca').hasClass('underline_show')) {\r\n");
      out.write("\t\t\t\t$('#about_pca').removeClass('underline_show');\r\n");
      out.write("\t\t\t\t$('#about_pca').addClass('underline_hide');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#about_all').click(\r\n");
      out.write("\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t$(this).removeClass(\"underline_hide\");\r\n");
      out.write("\t\t\t\t$(this).addClass(\"underline_show\");\t\r\n");
      out.write("\t\t\t\tif ($('#about_study').hasClass('underline_show')) {\r\n");
      out.write("\t\t\t\t\t$('#about_study').removeClass('underline_show');\r\n");
      out.write("\t\t\t\t\t$('#about_study').addClass('underline_hide');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif ($('#about_website').hasClass('underline_show')) {\r\n");
      out.write("\t\t\t\t\t$('#about_website').removeClass('underline_show');\r\n");
      out.write("\t\t\t\t\t$('#about_website').addClass('underline_hide');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif ($('#about_pca').hasClass('underline_show')) {\r\n");
      out.write("\t\t\t\t\t$('#about_pca').removeClass('underline_show');\r\n");
      out.write("\t\t\t\t\t$('#about_pca').addClass('underline_hide');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
