/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2021-04-03 11:02:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class resource_005fmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"Css/Public_style.css\" />\r\n");
      out.write("<link href=\"Css/Homepage.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"Css/resuorce.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"Css/Public_Color/orange.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");

   String id = request.getParameter("ID");
   String resource = request.getParameter("resource");
   String baidu = null;
   String bili = null;
   String abab = null;
   if("1".equals(resource)){
	   baidu="color";
   }else if("2".equals(resource)){
	   bili="color";
   }else if("3".equals(resource)){
	   abab="color";
   }else {
	   baidu="color";
   }
   
      out.write("\r\n");
      out.write("   <div class=\"resuorce_menu\">\r\n");
      out.write("       <div class=\"resuorce_menu_head\">\r\n");
      out.write("           <font class=\"middle-font\" style=\"color:#FFA980;\">导航</font>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"resuorce_menu_heads\" >\r\n");
      out.write("           <font class=\"small-font\" style=\"\">规则</font>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"resuorce_menu_b baidu color\" id=\"1\">\r\n");
      out.write("       <form action=\"resource_function.jsp\" method=\"post\" id=\"form_1\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"resource\" value=\"1\" style=\"display:none\"/>\r\n");
      out.write("                    <input type=\"text\" name=\"ID\" value=\"");
      out.print(id );
      out.write("\" style=\"display:none\"/>\r\n");
      out.write("          <a onclick=\"document:form_1.submit();\" class=\"");
      out.print(baidu );
      out.write("\"> <font class=\"small-font\">•&nbsp;百度云</font></a>\r\n");
      out.write("          \t</form>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"resuorce_menu_b bilibili\" id=\"2\">\r\n");
      out.write("        <form action=\"resource_function.jsp\" method=\"post\" id=\"form_2\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"resource\" value=\"2\" style=\"display:none\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"ID\" value=\"");
      out.print(id );
      out.write("\" style=\"display:none\"/>\r\n");
      out.write("          <a  onclick=\"document:form_2.submit();\" class=\"");
      out.print(bili );
      out.write("\"> <font class=\"small-font\">•&nbsp;哔哩哔哩</font></a>\r\n");
      out.write("          </form>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"resuorce_menu_b abab\" id=\"3\">\r\n");
      out.write("       <form action=\"resource_function.jsp\" method=\"post\" id=\"form_3\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"resource\" value=\"3\" style=\"display:none\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"ID\" value=\"");
      out.print(id );
      out.write("\" style=\"display:none\"/>\r\n");
      out.write("          <a  onclick=\"document:form_3.submit();\" class=\"");
      out.print(abab );
      out.write("\"> <font class=\"small-font\">•&nbsp;阿巴阿巴网盘</font></a>\r\n");
      out.write("          </form>\r\n");
      out.write("       </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script src=\"js/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('.resuorce_menu_b').click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('.resuorce_menu_b').removeClass(\"color\");\r\n");
      out.write("\t\t\t$(this).addClass(\"color\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write(" \r\n");
      out.write("\t});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
