/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2021-05-20 02:20:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class main_005fdown_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<div class=\"section\">\r\n");
      out.write("  <div class=\"about clear-fix\">\r\n");
      out.write("    <div class=\"maintitle\">关于我们 <span>about us</span> </div>\r\n");
      out.write("    <!-- end maintitle-->\r\n");
      out.write("    <div class=\"aboutCon\">\r\n");
      out.write("      <div class=\"aboutPic\"><img src=\"images/qrcode.png\" alt=\"关于我们\" width=\"120\" height=\"120\"></div>\r\n");
      out.write("      <div class=\"aboutConFont\"> <span>金斯科物流有限公司</span>　　金斯科物流有限公司资质、证照齐全，作业规范，送达及时，是一家集实力与规模于一体的货物运输公司。有着多年的运输经验，深受客户的信赖与好评。我公司备有各种运输车辆，专业从事全国各地的货物运输及配送服务。</div>\r\n");
      out.write("      <!-- end aboutConFont --> \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end aboutCon --> \r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- end about --> \r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("  <div class=\"linkBox\">\r\n");
      out.write("    <div class=\"link\">\r\n");
      out.write("      <div class=\"linkTitle\">友情链接</div>\r\n");
      out.write("      <div class=\"link_list\"> <a href=\"http://www.mingrisoft.com\" title=\"明日学院\" target=\"_blank\">明日学院</a> <a href=\"http://www.mingribook.com\" title=\"明日图书\" target=\"_blank\">明日图书</a> </div>\r\n");
      out.write("      <!-- end link_list-->\r\n");
      out.write("      <div class=\"clear\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end link--> \r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- end linkBox-->\r\n");
      out.write("  <div class=\"btnav\">\r\n");
      out.write("    <div class=\"footlink\"> <a href=\"mainPage.jsp\" title=\"网站首页\">网站首页</a>　 |　 <a href=\"http://www.mingrisoft.com\" title=\"关于我们\">关于我们</a> 　 |　 <a href=\"#\" title=\"运输线路\">运输线路</a> 　 |　 <a href=\"#\" title=\"服务项目\">服务项目</a> 　 |　 <a href=\"#\" title=\"企业资质\">企业资质</a> 　 |　 <a href=\"#\" title=\"车辆展示\">车辆展示</a> 　 |　 <a href=\"#\" title=\"行业资讯\">行业资讯</a> 　 |　 <a href=\"http://www.mingrisoft.com\" title=\"加入我们\">加入我们</a> 　 |　 <a href=\"#\" title=\"在线留言\">在线留言</a> 　 |　 <a href=\"http://www.mingrisoft.com\" title=\"联系我们\">联系我们</a> </div>\r\n");
      out.write("    <!-- end footlink--> \r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- end btnav-->\r\n");
      out.write("  <div class=\"copyright\"> 地址：吉林省长春市卫星广场财富领域5A15室　　电话：0431-84978981<br />\r\n");
      out.write("    版权所有：吉林省明日科技有限公司  吉ICP备 10002740号-2 吉公网安备22010202000132号</a> </div>\r\n");
      out.write("  <!-- end copyright--> \r\n");
      out.write("</div>\r\n");
      out.write("<!-- end footer-->\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
