/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2021-02-08 04:30:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Adminpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.Admin_tools;

public final class check_005fmission_005fdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.Admin_tools");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../Css/Public_style.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../Css/Assignment.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../Css/Public_Color/orange.css\" />\r\n");
      out.write("\t<body>\r\n");
      out.write("\t");

	request.setCharacterEncoding("UTF-8");
		String tips="";
		String name=request.getParameter("name");
		String tittle=request.getParameter("tittle");
		String difficult=request.getParameter("difficult");
		String type=request.getParameter("type");
		String language=request.getParameter("language");
		String nowpage=request.getParameter("nowpage");
		System.out.println(nowpage);
		String text=request.getParameter("text");	
		if(text==null){
			text="";
		}
		String missionID=request.getParameter("missionID");
		System.out.println(missionID);
		String pageID=request.getParameter("pageID");
		System.out.println(pageID);
		String ID=(String)request.getSession().getAttribute("ID");
		Admin_tools bean=new Admin_tools(ID);
		bean.getmissioninf(missionID, pageID);
		if("1".equals( request.getParameter("sub"))){
			if(!"0".equals(request.getParameter("point"))&&request.getParameter("text")!=null&&!"".equals(request.getParameter("text")))
			{	
				bean.subcharge(missionID, pageID, request.getParameter("text"), request.getParameter("point"));
				tips="提交成功";
				text="";
			}else{
				tips="内容未补完!";
			}
		}
	
      out.write("\r\n");
      out.write("\t\t\t<form action=\"check_mission.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div class=\"small-tittle middle-font font-normal-color\">\r\n");
      out.write("\t\t\t\t\t&nbsp;┃&nbsp;<button name=\"setlocal\" value=\"1\" style=\"height:100%;width=35px;border:0px solid white;background:#FAFAFA;\" class=\"middle-font font-normal-color\">\r\n");
      out.write("\t\t\t\t\t\t批改任务\r\n");
      out.write("\t\t\t\t\t</button>\t\t\t\r\n");
      out.write("\t\t\t\t\t<img src=\"../img/lead_photo/返回.png\" style=\"width:30px;height:25px;float:right;\">\r\n");
      out.write("\t\t\t\t\t<input name=\"jumpact\" value=\"");
      out.print(request.getParameter("nowpage") );
      out.write("\" type=\"text\"style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t<button name=\"setlocal\" value=\"1\" style=\"height:100%;float:right;width:150px;border:0px solid white;background:#FAFAFA;\" class=\"middle-font font-normal-color\">\r\n");
      out.write("\t\t\t\t\t\t返回上一级\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form><div style=\"width:49.5%;height:500px;float:left;\">\r\n");
      out.write("\t\t\t\t<div class=\"small-tittle middle-font font-normal-color\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t\t&nbsp;-&nbsp;内容\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<textarea style=\"width:100%;height:600px;border:0px solid white;\">");
      out.print(bean.missionfinishcontent );
      out.write("</textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"width:49.5%;height:500px;margin-left:1%;float:left;\">\r\n");
      out.write("\t\t\t\t<div class=\"small-tittle middle-font font-normal-color\" style=\"width:75%;float:left;\">\r\n");
      out.write("\t\t\t\t\t&nbsp;-&nbsp;作业要求\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"small-tittle middle-font font-normal-color\" style=\"width:24.9%;margin-left:0.1%;float:left;\">\r\n");
      out.write("\t\t\t\t\t&nbsp;-&nbsp;作业信息\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<textarea style=\"width:75%;height:200px;border:0px solid white;float:left;\">");
      out.print(bean.missioninf );
      out.write(" </textarea>\r\n");
      out.write("\t\t\t\t<div style=\"width:24.9%;margin-left:0.1%;float:left;height:200px;font-size:20px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"light-color\" style=\"width:35%;float:left;width:100%;line-height:25px;height:25px;color:white;\"align=\"center\">提交者</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dinylight-color\" style=\"width:35%;float:left;width:100%;line-height:25px;height:25px;color:gray;\"align=\"center\">");
      out.print(name );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"light-color\" style=\"width:35%;float:left;width:100%;line-height:25px;height:25px;color:white;\"align=\"center\">任务类型</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dinylight-color\" style=\"width:35%;float:left;width:100%;line-height:25px;height:25px;color:gray;\"align=\"center\">");
      out.print(type);
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"light-color\" style=\"width:35%;float:left;width:100%;line-height:25px;height:25px;color:white;\"align=\"center\">任务语言</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dinylight-color\" style=\"width:35%;float:left;width:100%;line-height:25px;height:25px;color:gray;\"align=\"center\">");
      out.print(language );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"light-color\" style=\"width:35%;float:left;width:100%;height:25px;line-height:25px;color:white;\"align=\"center\">难度</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dinylight-color\" style=\"width:35%;float:left;width:100%;line-height:25px;height:25px;color:gray;\"align=\"center\">");
      out.print(difficult );
      out.write("</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<form action=\"check_mission_details.jsp\"method=\"post\">\r\n");
      out.write("\t\t\t\t\t<input name=\"nowpage\" value=\"");
      out.print(nowpage );
      out.write("\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t<input style=\"display:none;\"name=\"missionID\"value=\"");
      out.print(missionID );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<input style=\"display:none;\"name=\"pageID\"value=\"");
      out.print(pageID );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<input style=\"display:none;\"name=\"name\"value=\"");
      out.print(name );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<input style=\"display:none;\"name=\"type\"value=\"");
      out.print(type );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<input style=\"display:none;\"name=\"language\"value=\"");
      out.print(language );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<input style=\"display:none;\"name=\"difficult\"value=\"");
      out.print(difficult );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<div class=\"light-color\" style=\"width:100%;float:left;width:100%;height:25px;line-height:25px;color:white;\"align=\"center\">编写评价</div>\r\n");
      out.write("\t\t\t\t\t<textarea style=\"width:100%;height:270px;border:0px solid white;\" name=\"text\">");
      out.print(text );
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t<div class=\"light-color\" style=\"width:100%;float:left;width:100%;height:25px;line-height:25px;\"align=\"center\">评级</div>\r\n");
      out.write("\t\t\t\t\t<select name=\"point\" style=\"width:100%;height:35px;\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">--</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">A+</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">A</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">B</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">C</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<button name=\"sub\" value=\"1\" style=\"width:100%;height:45px;border:0px solid white;border-radius:4px;\"class=\"light-color\">提交</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<div style=\"width:100%;height:25px;color:red;line-height:25px;font-size:20px;\"align=\"center\">");
      out.print(tips );
      out.write("</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
