/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2021-03-19 06:00:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Adminpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bean.member_menage;

public final class number_005fmenage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bean.member_menage");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>成员管理</title>\r\n");
      out.write("</head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../Css/Public_style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../Css/Assignment.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../Css/Public_Color/orange.css\" />\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		request.setCharacterEncoding("UTF-8");
	String ID=(String)request.getSession().getAttribute("ID");
	if(ID==null||"".equals(ID)||"null".equals(ID)){
		request.setAttribute("alter", "1");
		request.getRequestDispatcher("index.jsp").forward(request, response);
	}
		String nowpage = request.getParameter("nowpage");
		if (nowpage == null || "".equals(nowpage) || "null".equals(nowpage)) {
			nowpage = "1";
		}
		String act = request.getParameter("act");
		if (act != null && !"".equals(act) && !"null".equals(act)) {
			if ("1".equals(act)) {
				nowpage = 1 + "";
			} else if ("2".equals(act) && Integer.parseInt(nowpage) > 1) {
				nowpage = Integer.parseInt(nowpage) - 1 + "";
			} else if ("3".equals(act)) {
				nowpage = request.getParameter("jumppage");
			} else if ("4".equals(act)
					&& Integer.parseInt(nowpage) < Integer.parseInt(request.getParameter("allpage"))) {
				nowpage = Integer.parseInt(nowpage) + 1 + "";
			} else if ("5".equals(act)) {
				nowpage = request.getParameter("allpage");
			}
		}
		

		String select_name = null;
		String select_ID = null;
		String select_role = null;
		if (request.getParameter("chose") != null) {
			select_name = request.getParameter("select_name");
			select_ID = request.getParameter("select_ID");
			select_role = request.getParameter("select_role");
		}
		if (select_name == null) {
			select_name = "";
		}
		if (select_ID == null) {
			select_ID = "";
		}
		if (select_role == null) {
			select_role = "";
		}
		member_menage bean = new member_menage(ID);
		String role[] = bean.getroles();
		bean.getIDs(select_name, select_ID, select_role, nowpage);
		String pageurl = "change_show.jsp";
		String changeID = "";
		if (request.getParameter("changeshow") != null) {
			pageurl = "change_show.jsp";
			changeID = request.getParameter("changerole");
			request.getSession().setAttribute("changeID", changeID);
		} else if (request.getParameter("changerole") != null) {
			pageurl = "change_user_role.jsp";
			changeID = request.getParameter("changerole");
			request.getSession().setAttribute("changeID", changeID);
		} else if (request.getParameter("changedata") != null) {
			pageurl = "change_data.jsp";
			changeID = request.getParameter("changedata");
			request.getSession().setAttribute("changeID", changeID);
		}
		System.out.println(pageurl);
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Admin_lead.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("block_id", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("7", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\t<div style=\"width: 87.5%; margin-left: 0.1%; height: 824px; float: left;\" class=\"dinylight-color\">\r\n");
      out.write("\t\t<div class=\"small-tittle middle-font font-normal-color\">&nbsp;┃&nbsp;成员管理</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div style=\"width: 100%; margin-bottom: 2px; height: 45px; float: left; line-height: 45px; color: white;\" class=\"light-color\">\r\n");
      out.write("\t\t\t<form action=\"number_menage.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div style=\"width: 50%; height: 45; float: left;\">\r\n");
      out.write("\t\t\t\t\t<font style=\"margin-left: 2%;\">姓名:&nbsp;</font>\r\n");
      out.write("\t\t\t\t\t<input value=\"");
      out.print(select_name);
      out.write("\" name=\"select_name\" style=\"width: 20%; border-radius: 3px; margin-top: 11px; height: 21px; border: 1px solid gray;\" />\r\n");
      out.write("\t\t\t\t\t<font style=\"margin-left: 2%;\">账号:&nbsp;</font>\r\n");
      out.write("\t\t\t\t\t<input value=\"");
      out.print(select_ID);
      out.write("\" name=\"select_ID\" style=\"width: 20%; border-radius: 3px; margin-top: 11px; height: 21px; border: 1px solid gray;\" />\r\n");
      out.write("\t\t\t\t\t<font style=\"margin-left: 2%;\">角色:&nbsp;</font>\r\n");
      out.write("\t\t\t\t\t<select name=\"select_role\" style=\"width: 20%; border-radius: 3px; margin-top: 11px; height: 21px; border: 1px solid gray;\">\r\n");
      out.write("\t\t\t\t\t\t");

							if (select_role != null && !"".equals(select_role) && !"null".equals(select_role)) {
								int getrole = Integer.parseInt(select_role);
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(getrole);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(role[getrole - 1]);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">--</option>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">--</option>\r\n");
      out.write("\t\t\t\t\t\t");

							}
							for (int a = 1; a <= role.length; a++) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(a);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(role[a - 1]);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button name=\"chose\" value=\"1\" style=\"line-height: 31px; float: left; margin-right: 5%; margin-top: 6px; height: 31px; width: 15%; color: #FFA980; background-color: white; border: 0px solid white; border-radius: 4px;\">筛选</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<form action=\"number_menage.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input style=\"display: none;\" name=\"chose\" value=\"");
      out.print(request.getParameter("chose"));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input style=\"display: none;\" name=\"select_name\" value=\"");
      out.print(select_name);
      out.write("\">\r\n");
      out.write("\t\t\t\t<input style=\"display: none;\" name=\"select_ID\" value=\"");
      out.print(select_ID);
      out.write("\">\r\n");
      out.write("\t\t\t\t<input style=\"display: none;\" name=\"select_role\" value=\"");
      out.print(select_role);
      out.write("\">\r\n");
      out.write("\t\t\t\t<input style=\"display: none;\" name=\"nowpage\" value=\"");
      out.print(nowpage);
      out.write("\">\r\n");
      out.write("\t\t\t\t<button name=\"changeshow\" value=\"1\" style=\"line-height: 31px; float: left; margin-left: 5%; margin-top: 6px; height: 31px; width: 15%; color: #FFA980; background-color: white; border: 0px solid white; border-radius: 4px;\">角色管理</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div style=\"width: 100%;\">\r\n");
      out.write("\t\t\t<div style=\"width: 65%; float: left;\">\r\n");
      out.write("\t\t\t\t<div style=\"float: left; width: 100%; font-size: 17px; line-height: 35px; height: 35px; margin-top: 2px; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t<div style=\"color: white; width: 10%; heigth: 35px; float: left;\" class=\"light-color\">序号</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"color: white; width: 25%; heigth: 35px; float: left; margin-left: 0.1%;\" class=\"light-color\">账号</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 20%; color: white; heigth: 35px; float: left; margin-left: 0.1%;\" class=\"light-color\">姓名</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 15%; heigth: 35px; float: left; color: white; margin-left: 0.1%;\" class=\"light-color\">角色</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 29.5%; heigth: 35px; float: left; color: white; margin-left: 0.1%;\" class=\"light-color\">操作</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");

					for (int a = 0; a < bean.showdata; a++) {
						String color = "";
						if (a % 2 == 0) {
							color = "dinylight-color";
						} else {
							color = "white-color";
						}
				
      out.write("\r\n");
      out.write("\t\t\t\t<div style=\"color: gray; width: 100%; font-size: 15px; line-height: 25px; height: 25px; margin-top: 2px; float: left; text-align: center;\" class=\"");
      out.print(color);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 10%; heigth: 25px; float: left;\">");
      out.print(a + 1 + ((Integer.parseInt(nowpage) - 1) * 20));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 25%; heigth: 25px; float: left; margin-left: 0.1%;\">");
      out.print(bean.allID.get(a));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 20%; heigth: 25px; float: left; margin-left: 0.1%;\">");
      out.print(bean.allname.get(a));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 15%; heigth: 25px; float: left; margin-left: 0.1%;\">");
      out.print(role[Integer.parseInt(bean.allrole.get(a)) - 1]);
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 29.5%; heigth: 25px; float: left; margin-left: 0.1%;\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"number_menage.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<input style=\"display: none;\" name=\"chose\" value=\"");
      out.print(request.getParameter("chose"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<input style=\"display: none;\" name=\"select_name\" value=\"");
      out.print(select_name);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<input style=\"display: none;\" name=\"select_ID\" value=\"");
      out.print(select_ID);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<input style=\"display: none;\" name=\"select_role\" value=\"");
      out.print(select_role);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<input style=\"display: none;\" name=\"nowpage\" value=\"");
      out.print(nowpage);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								String border1 = "border: 0px solid white;";
									String border2 = "border: 0px solid white;";
									if (bean.allID.get(a).equals((String) request.getSession().getAttribute("changeID"))) {
										if ("change_data.jsp".equals(pageurl)) {
											border2 = "border:2px solid gray;";
											border1 = " border: 0px solid white;";
										} else {
											border2 = "border:0px solid gray;";
											border1 = "border:2px solid gray;";
										}

									}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button name=\"changerole\" value=\"");
      out.print(bean.allID.get(a));
      out.write("\" style=\"");
      out.print(border1);
      out.write(" color: white; width: 35%; height: 100%; border-radius: 5px; \" class=\"light-color\">角色</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button name=\"changedata\" value=\"");
      out.print(bean.allID.get(a));
      out.write("\" style=\"");
      out.print(border2);
      out.write(" color: white; background-color: #84BFD9; margin-left: 0.1%; width: 35%; height: 100%; border-radius: 5px;\">编辑</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"turnpage-conntrol light-color\" style=\"color: gray; height: 45px; padding-top: 2px; margin-top: 3px;\">\r\n");
      out.write("\t\t\t\t\t<div style=\"width: 100%; height: 15px; margin-bottom: 3px; line-height: 15px;\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t");

							int num = bean.datanum;
							int allpage = 0;
							for (;;) {
								num = num - 20;
								if (num == -20) {
									allpage = 1;
									break;
								} else if (num > -20 && num <= 0) {
									allpage = allpage + 1;
									break;
								} else if (num > 0) {
									allpage = allpage + 1;
								}
							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<font color=\"white\">\r\n");
      out.write("\t\t\t\t\t\t\t当前第");
      out.print(nowpage);
      out.write("页/共有");
      out.print(allpage);
      out.write('页');
      out.print(bean.datanum);
      out.write("条记录\r\n");
      out.write("\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<form action=\"number_menage.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input style=\"display: none;\" name=\"select_name\" value=\"");
      out.print(select_name);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input style=\"display: none;\" name=\"select_ID\" value=\"");
      out.print(select_ID);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input style=\"display: none;\" name=\"select_role\" value=\"");
      out.print(select_role);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input style=\"display: none;\" name=\"allpage\" value=\"");
      out.print(allpage);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input style=\"display: none;\" name=\"nowpage\" value=\"");
      out.print(nowpage);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<div align=\"center\" style=\"width: 100%; height: 25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<button name=\"act\" value=\"1\" class=\"dinylight-color\" style=\"border-radius: 2px; height: 25px; width: 12%; border: 0px solid white;\">首页</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button name=\"act\" value=\"2\" class=\"dinylight-color\" style=\"border-radius: 2px; height: 25px; width: 12%; border: 0px solid white;\">上一页</button>\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"jumppage\" style=\"width: 6%; height: 25px; border: 0px solid white; border-radius: 2px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"");
      out.print(nowpage);
      out.write('"');
      out.write('>');
      out.print(nowpage);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									for (int a = 1; a <= allpage; a++) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"");
      out.print(a);
      out.write('"');
      out.write('>');
      out.print(a);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t<button name=\"act\" value=\"3\" class=\"dinylight-color\" style=\"border-radius: 2px; height: 25px; width: 6%; border: 0px solid white;\">跳转</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button name=\"act\" value=\"4\" class=\"dinylight-color\" style=\"border-radius: 2px; height: 25px; width: 12%; border: 0px solid white;\">下一页</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button name=\"act\" value=\"5\" class=\"dinylight-color\" style=\"border-radius: 2px; height: 25px; width: 12%; border: 0px solid white;\">尾页</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"width: 0.1%; height: 625px; background-color: black; float: left;\"></div>\r\n");
      out.write("\t\t\t<div style=\"width: 34.8%; height: 625px; background-color: white; float: left; margin-left: 0.1%; margin-top: 2px;\">\r\n");
      out.write("\t\t\t\t<iframe style=\"width: 100%; height: 100%; border: 0px solid white;\" src=\"");
      out.print(pageurl);
      out.write("\"></iframe>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 翻页 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
