/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2021-03-19 06:00:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Adminpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bean.sendtext_bean;
import dao.sendtext;
import java.util.StringTokenizer;

public final class sendtext_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bean.sendtext_bean");
    _jspx_imports_classes.add("java.util.StringTokenizer");
    _jspx_imports_classes.add("dao.sendtext");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<title>Insert title here</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../Css/Public_Color/orange.css\" />\r\n");
      out.write("\t\t<link href=\"../Css/Public_style.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t<form action=\"send_notice.jsp\" method=\"post\">\r\n");
      out.write("\t\t<div style=\"width:100%;height:700px\">\r\n");
      out.write("\t\t\t<div style=\"width:10%;height:100%;float:left;\">\r\n");
      out.write("\t\t\t\t");

					request.setCharacterEncoding("UTF-8");
					int nowpage=1;
					String tips="";
					if(request.getParameter("act")!=null&&!"".equals( request.getParameter("act"))&&!"null".equals( request.getParameter("act"))){
					int allpage=Integer.parseInt( request.getParameter("allpage"));
					nowpage=Integer.parseInt(request.getParameter("nowpage"));
					int topage=Integer.parseInt( request.getParameter("topage"));
					String act=request.getParameter("act");
					if("1".equals(act)){
						if(nowpage-1>0){
							nowpage=nowpage-1;
						}
					}else if("2".equals(act)){
						nowpage=topage;
					}else if("3".equals(act)){
						if(nowpage+1<=allpage){
							nowpage=nowpage+1;
						}
					}									
				}				
				String role=request.getParameter("role");
				if(role==null||"".equals(role)||"null".equals(role)){
					role="0";
				}
				System.out.println("role:"+role);
				String ID=(String)request.getSession().getAttribute("ID");
				sendtext_bean bean=new sendtext_bean(ID);
				String userrole=bean.getuserrole();
				StringTokenizer chart=new StringTokenizer(userrole,"_");
			
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"small-tittle middle-font font-normal-color\" style=\"margin-bottom:2px;float:left;width:100%;margin-right:0.2%;\">\r\n");
      out.write("\t\t\t\t\t\t&nbsp;-&nbsp;职位\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");
	
				String color="";
				int num=chart.countTokens()/2;
				for(int a=-1;a<num;a++){
					if(a+1==Integer.parseInt(role)){
						color="light-color";
					}else{
						color="white-color";
					}
					if(a<0){
			
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul style=\"float:left;width:100%;list-style-type: none;\">\r\n");
      out.write("\t\t\t\t\t\t<li style=\"width:100%;height:38px;line-height:35px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:100%;height:35px;line-height:35px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button style=\"cursor:pointer;width:100%;height:100%;border:0px solid white;\" name=\"role\" class=\"");
      out.print(color );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t value=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t全部成员</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t");
 }else{
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul style=\"float:left;width:100%;list-style-type: none;\">\r\n");
      out.write("\t\t\t\t\t\t<li style=\"width:100%;height:38px;line-height:35px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:100%;height:35px;line-height:35px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button style=\"cursor:pointer;width:100%;height:100%;border:0px solid white;\" name=\"role\" class=\"");
      out.print(color );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t value=\"");
      out.print(chart.nextToken() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(chart.nextToken() );
      out.write("</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

					}} 
			
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");
System.out.println("+++++++++++++++++++++++++++++++++++");
				String sendID=(String)request.getSession().getAttribute("ID");
				String getersID=(String)request.getParameter("geterID");
				String getrole=request.getParameter("role");
				String send=request.getParameter("send");
				String gettype=request.getParameter("gettype");
				String tittle=request.getParameter("tittle");
				String content=request.getParameter("content");
				if(tittle==null||"null".equals(tittle)){
					tittle="";
				}
				if(content==null||"null".equals(content)){
					content="";
				}
	
				sendtext sendmessage=new sendtext();
				if("1".equals(send)){
					if("1".equals(gettype)){
						if(content==null||"".equals(content)||"null".equals(content)){
							tips="内容未补完";
						}else if(getersID==null||"".equals(getersID)||"null".equals(getersID)){
							tips="未选择接收人";
							}else{						
							sendmessage.send(sendID,getersID,getrole,gettype,tittle,content);
							content="";
							tips="发送成功";
						}
					}else{
					if(tittle==null||"".equals(tittle)||"null".equals(tittle)){
						tips="标题未补完";
					}else if(content==null||"".equals(content)||"null".equals(content)){
						tips="内容未补完";
						}else if(getersID==null||"".equals(getersID)||"null".equals(ID)){
							tips="未选择接收人";
							}else{
							sendmessage.send(sendID,getersID,getrole,gettype,tittle,content);
							content="";
							tittle="";
							tips="发送成功";
						}
					}
				}
				
				
				
				
				
				System.out.println("+++++++++++++++++++++++++++++++++++");
				
      out.write("\r\n");
      out.write("\t\t\t\t<div style=\"width:0.1%;height:100%;background-color:gray;float:left;\"> </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div style=\"width:35%;height:100%;float:left;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"small-tittle middle-font font-normal-color\" style=\"margin-bottom:2px;float:left;width:100%;margin-right:0.2%;\">\r\n");
      out.write("\t\t\t\t\t\t&nbsp;-&nbsp;接收人\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<ul style=\"float:left;width:100%;list-style-type: none;\">\r\n");
      out.write("\t\t\t\t\t\t");

			String checkID=request.getParameter("geterID");
			String checker="";
			if(bean.equal("@E_E", checkID)){
				System.out.println("选中");
				checker="checked='checked'";
			}
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li style=\"cursor:pointer;width:100%;height:38px;line-height:35px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:100%;height:35px;line-height:35px;background-color:white;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"geterID\" value=\"0\" style=\"float:left;margin-top:12px;\" ");
      out.print(checker );
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:35px;height:35px;float:left;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"../img/head_photo/1.jpg\" style=\"width:25px;height:25px;margin-top:5px;margin-left:3px;border-radius:20px;border:1px solid gray;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;全体成员\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t");

				bean.getuser(role, nowpage);
				StringTokenizer chart1=new StringTokenizer(bean.ID_headphoto,"鰶");
				StringTokenizer chart2=new StringTokenizer(bean.usersname,"鰶");
				int num2=chart2.countTokens();
				
				System.out.println("checkerID"+checkID);
				for(int b=0;b<num2;b++){
					
					String geterID=chart1.nextToken();
					System.out.println("geterID"+geterID);
					checker="";
					if(bean.equal(geterID, checkID)){
						System.out.println("选中");
						checker="checked='checked'";
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li style=\"cursor:pointer;width:100%;height:38px;line-height:35px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width:100%;height:35px;line-height:35px;background-color:white;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"geterID\" value=\"");
      out.print(geterID );
      out.write("\" style=\"float:left;margin-top:12px;\" ");
      out.print(checker );
      out.write(" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:35px;height:35px;float:left;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"../img/head_photo/");
      out.print(chart1.nextToken() );
      out.write(".jpg\" style=\"width:25px;height:25px;margin-top:5px;margin-left:3px;border-radius:20px;border:1px solid gray;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(chart2.nextToken() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t");

					}
				int allpage=0;
				int num1=bean.countuser;
					for (;;) {
						num1 = num1 - 15;
						if(num1==-15){
							allpage=1;
							break;
						}else if (num1 > -15 && num1 <= 0) {
							allpage = allpage  + 1;							
							break;
						} else if (num1 > 0) {
							allpage  = allpage  + 1;
						}
					}
				
				
				
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<input name=\"role\" value=\"");
      out.print(role );
      out.write("\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t<input name=\"allpage\" value=\"");
      out.print(allpage );
      out.write("\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t<input name=\"nowpage\" value=\"");
      out.print(nowpage );
      out.write("\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t<div style=\"width:100%;\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<font>第\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(nowpage );
      out.write("页/共\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(allpage );
      out.write("页\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(bean.countuser );
      out.write("位同学\r\n");
      out.write("\t\t\t\t\t\t</font> <br />\r\n");
      out.write("\t\t\t\t\t\t<button name=\"act\" value=\"1\" style=\"cursor:pointer;background-color: #FFCAB0;  width: 23%; height: 30px; border-radius: 5px; border: 0px solid lightgray;\">上一页</button>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"topage\" style=\"width: 23%;height: 30px;border-radius:5px;background-color:#FFCAB0;border:0px solid white;\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(nowpage );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(nowpage );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								for(int c=0;c<allpage ;c++)
								{ 
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(c+1 );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(c+1 );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} 
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<button name=\"act\" value=\"2\" style=\"cursor:pointer;background-color: #FFCAB0;  width: 23%; height: 30px; border-radius: 5px; border: 0px solid lightgray;\">跳转</button>\r\n");
      out.write("\t\t\t\t\t\t<button name=\"act\" value=\"3\" style=\"cursor:pointer;background-color: #FFCAB0;  width: 23%; height: 30px; border-radius: 5px; border: 0px solid lightgray;\">下一页</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div style=\"width:0.1%;height:100%;background-color:gray;float:left;\"> </div>\r\n");
      out.write("\t\t\t\t<!-- 填写消息模块 -->\r\n");
      out.write("\t\t\t\t<div style=\"width:54.8%;height:100%;float:left;\">\r\n");
      out.write("\t\t\t\t\t");
	String color1="dinylight-color";
						String color2="dinylight-color";
						String color3="dinylight-color";
						if(bean.countuser==0){
							tips="无成员";
						}
						String messagetype=request.getParameter("messagetype");
						if("1".equals(request.getParameter("send"))){
							
							messagetype=request.getParameter("gettype");
						}
						if(messagetype==null||"".equals(messagetype)||"null".equals(messagetype)){
							messagetype="1";
						}
						if("1".equals(messagetype)){						
							color1="light-color";
							out.println("<input name='gettype' value='1'style='display:none;'/>");
						}
						if("2".equals(messagetype)){
							color2="light-color";
							out.println("<input name='gettype' value='2'style='display:none;'/>");
						}	
						if("3".equals(messagetype)){						
							color3="light-color";
							out.println("<input name='gettype' value='3'style='display:none;'/>");
						}		
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"small-tittle middle-font font-normal-color\" style=\"margin-bottom:2px;float:left;width:100%;margin-right:0.2%;\">\r\n");
      out.write("\t\t\t\t\t\t&nbsp;-&nbsp;消息类型\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width:100%;height:33px;background-color:white;float:left;\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"role\" value=\"");
      out.print(role );
      out.write("\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"allpage\" value=\"");
      out.print(allpage );
      out.write("\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"nowpage\" value=\"");
      out.print(nowpage );
      out.write("\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<ul style=\"width:30%;height:35px;float:left;list-style-type: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:32px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button style=\"line-height:30px;width:100%;height:30px;border:0px solid white;\" class=\"");
      out.print(color1 );
      out.write("\" name=\"messagetype\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t value=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;-&nbsp;短消息\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<ul style=\"width:30%;height:40px;float:left;line-height:35px;list-style-type: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:32px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button style=\"line-height:30px;width:100%;height:30px;border:0px solid white;\" class=\"");
      out.print(color2 );
      out.write("\" name=\"messagetype\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t value=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;-&nbsp;通知消息\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<ul style=\"width:30%;height:40px;float:left;line-height:35px;list-style-type: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:32px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button style=\"line-height:30px;width:100%;height:30px;border:0px solid white;\" class=\"");
      out.print(color3 );
      out.write("\" name=\"messagetype\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t value=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;-&nbsp;作业提醒\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width:100%;height:700px;float:left;\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t");
if("1".equals( messagetype)){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"small-tittle middle-font font-normal-color\" style=\"margin-bottom:2px;float:left;width:100%;margin-right:0.2%;\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;-&nbsp;内容&nbsp;-&nbsp;\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input style=\"width:98%;height:30px;font-size:20px;line-height:30px;\" name=\"content\" value=\"");
      out.print(content );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t");
if(bean.countuser>0){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" name=\"send\" value=\"1\" style=\"width:65%;height:30px;line-height:30px;font-size:20px;border:0px solid white;border-radius:3px;margin-top:7px;color:white;\"\r\n");
      out.write("\t\t\t\t\t\t class=\"light-color\">\r\n");
      out.write("\t\t\t\t\t\t\t发送\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width:100%;height:25px;line-height:25px;font-size:15px;color:red;\" align=\"center\" id=\"tips\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(tips );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"small-tittle middle-font font-normal-color\" style=\"margin-bottom:2px;float:left;width:100%;margin-right:0.2%;\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;-&nbsp;标题&nbsp;-&nbsp;\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input style=\"width:98%;height:30px;font-size:20px;line-height:30px;\" name=\"tittle\" value=\"");
      out.print(tittle );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"small-tittle middle-font font-normal-color\" style=\"margin-bottom:2px;float:left;width:100%;margin-right:0.2%;\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;-&nbsp;内容&nbsp;-&nbsp;\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<textarea style=\"width:98%;height:300px;font-size:15px;\"name=\"content\">");
      out.print(content );
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t");
if(bean.countuser>0){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" name=\"send\" value=\"1\" style=\"width:65%;height:30px;line-height:30px;font-size:20px;border:0px solid white;border-radius:3px;margin-top:7px;color:white;\"\r\n");
      out.write("\t\t\t\t\t\t class=\"light-color\">\r\n");
      out.write("\t\t\t\t\t\t\t发送\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width:100%;height:25px;line-height:25px;font-size:15px;color:red;\" align=\"center\" id=\"tips\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(tips );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar list = document.getElementsByTagName(\"li\");\r\n");
      out.write("\t\tfor (var i = 0; i < list.length; i++) {\r\n");
      out.write("\t\t\t//为li注册鼠标进入事件\r\n");
      out.write("\t\t\tlist[i].onmouseover = function() {\r\n");
      out.write("\t\t\t\tthis.style.backgroundColor = \"#FFCAB0\";\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t//为li注册鼠标离开事件\r\n");
      out.write("\t\t\tlist[i].onmouseout = function() {\r\n");
      out.write("\t\t\t\t//恢复到这个标签默认的颜色\r\n");
      out.write("\t\t\t\tthis.style.backgroundColor = \"\";\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
