/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2021-03-19 06:00:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Adminpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.journal_tool;
import java.util.StringTokenizer;

public final class web_005fjournal_005fchild_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.journal_tool");
    _jspx_imports_classes.add("java.util.StringTokenizer");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(".jo_turnpage-turn {\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tline-height: 35px;\r\n");
      out.write("\tfont-size: 28px;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin-left: 6px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tborder-radius: 6px;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".jo_turnpage-number {\r\n");
      out.write("\twidth: 15%;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tline-height: 30px;\r\n");
      out.write("\tfont-size: 28px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-left: 6px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tborder-radius: 6px;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".jo_turnpage-foin {\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tmargin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".jo_turnpage-conntrol {\r\n");
      out.write("\tmargin-top: 1%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin-left: 4%;\r\n");
      out.write("\theight: 45px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".body_charge {\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head_charge {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 70px;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".stoma_charge {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 630px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tbackground-color: #FFE4D7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tail_charge {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 70px;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".excel {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 15%;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tmargin-top: 17px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tline-height: 40px;\r\n");
      out.write("\tcolor: #FFA980;\r\n");
      out.write("\tborder-left: 1px solid #FAE441;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".excel_content {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 15%;\r\n");
      out.write("\theight: 34px;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tmargin-top: 1px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 34px;\r\n");
      out.write("\tborder-left: 1px solid #FAE441;\r\n");
      out.write("\toverflow-x: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".border_line {\r\n");
      out.write("\theight: 1px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tborder-bottom: 1px solid #FAE441;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		request.setCharacterEncoding("UTF-8");//或者指定的编码(GBK或其他)
		String needsearch_type = null;
		String needsearch_content = null;
		if (request.getParameter("needsearch_type") != null) {
			needsearch_type = request.getParameter("needsearch_type");
		}
		if (request.getParameter("needsearch_content") != null) {
			needsearch_content = request.getParameter("needsearch_content");
		}
		String nowpages = request.getParameter("nowpage");//传值给当前页码
		int nowpage;//真*当前页码
		if (nowpages == null || nowpages.equals("")) { //安全设置
			nowpage = 1;
		} else {
			try {
				//把接收的值赋值给当前页码
				nowpage = Integer.parseInt(nowpages.trim());//Integer.parseInt String强转Int类型  .tirm()去掉两端空格
			} catch (NumberFormatException e) {
				nowpage = 1;
			}
			if (nowpage <= 0) //安全设置
				nowpage = nowpage + 1;
		}
		String type = null;
		if (request.getParameter("type") != null) {
			type = request.getParameter("type");
		}
		journal_tool jt = new journal_tool();
		if (type.equals("2")&&(needsearch_content==null||needsearch_content.equals("")||needsearch_content.equals("null"))) {
			String usename =  request.getParameter("needsearch_2_usename");
			String useID =  request.getParameter("needsearch_2_useID");
			String cotent =  request.getParameter("needsearch_2_cotent");
			String btime =  request.getParameter("needsearch_2_begintime");
			String ctime =  request.getParameter("needsearch_2_endtime");
			String sql = jt.sqlCatchup(usename, useID, cotent, btime, ctime);
			needsearch_content = sql;	
		}
		int pageSize = 17;//设置页面最大记录数
		int allRecord = jt.get_allRecord("journal", type, needsearch_type, needsearch_content);//全部记录
		int allPages = allRecord / pageSize + 1;//总页数(allpages)=总记录数/每页显示数+1

		//安全设置
		if (nowpage > allPages) {
			nowpage = allPages;
		}

		int startRecord = (nowpage - 1) * pageSize;
		//最后一页的记录数
		int nowpage_lines = pageSize;
		if (nowpage == allPages) {
			nowpage_lines = allRecord % pageSize;
		}

		/*------------------------------*/
		String need_search = "usename,useID,cotent,time,inname,inID";//查询字段 发布人id、标题、发布日期、详情ID
		String content = null;
		if (type.equals("1")) {
			content = jt.get_pageData(startRecord, pageSize, "journal", need_search, type,"", "");
		}
		if (type.equals("2")) {
			content = jt.get_pageData(startRecord, pageSize, "journal", need_search, type,"",needsearch_content);
		}
		if (type.equals("6") || type.equals("3") || type.equals("4") || type.equals("5")) {
			content = jt.get_pageData(startRecord, pageSize, "journal", need_search, type, needsearch_type,needsearch_content);
		}

		/*------------------------------*/
	
      out.write("\r\n");
      out.write("\t<div class=\"head_charge\">\r\n");
      out.write("\t\t<div class=\"excel\" style=\"border: 0; margin-left: 0.4%;\">用户</div>\r\n");
      out.write("\t\t<div class=\"excel\">用户ID</div>\r\n");
      out.write("\t\t<div class=\"excel\" style=\"width: 23.8%\">操作</div>\r\n");
      out.write("\t\t<div class=\"excel\">时间</div>\r\n");
      out.write("\t\t<div class=\"excel\">受影响人</div>\r\n");
      out.write("\t\t<div class=\"excel\">受影响人ID</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"stoma_charge\">\r\n");
      out.write("\t\t");

			StringTokenizer textline_cut = new StringTokenizer(content, "轎藎燼");//new 一个字符串剪切对象
			String text_line = "";//定义临时变量存储总字串
			for (int a = 0; a < nowpage_lines; a++) {
				text_line = textline_cut.nextToken(); //获取数据字符串
				StringTokenizer line_cut = new StringTokenizer(text_line, "麤讜黌");//new 一个子字符串剪切对象
				String username = line_cut.nextToken();
				String userID = line_cut.nextToken();
				String dowhat = line_cut.nextToken();
				String dotime = line_cut.nextToken();
				String infeer_name = line_cut.nextToken();
				String infeerID = line_cut.nextToken();
				if (infeer_name.equals("null") || infeer_name.equals("") || infeer_name == null) {
					infeer_name = "无";
				}
				if (infeerID.equals("null") || infeerID.equals("") || infeerID == null) {
					infeerID = "无";
				}
				if (a % 2 == 0) {
		
      out.write("\r\n");
      out.write("\t\t<div class=\"excel_content light-color white-font\"\r\n");
      out.write("\t\t\tstyle=\"border: 0; margin-left: 0.4%;\">");
      out.print(username);
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"excel_content light-color white-font\">");
      out.print(userID);
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"excel_content light-color white-font\"\r\n");
      out.write("\t\t\tstyle=\"width: 23.8%;\">");
      out.print(dowhat);
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"excel_content light-color white-font\">");
      out.print(dotime);
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"excel_content light-color white-font\">");
      out.print(infeer_name);
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"excel_content light-color white-font\">");
      out.print(infeerID);
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"border_line\"></div>\r\n");
      out.write("\t\t");

			} else {
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"excel_content dinylight-color font-normal-color\"\r\n");
      out.write("\t\t\tstyle=\"border: 0; margin-left: 0.4%;\">");
      out.print(username);
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"excel_content dinylight-color font-normal-color\">");
      out.print(userID);
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"excel_content dinylight-color font-normal-color\"\r\n");
      out.write("\t\t\tstyle=\"width: 23.8%;\">");
      out.print(dowhat);
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"excel_content dinylight-color font-normal-color\">");
      out.print(dotime);
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"excel_content dinylight-color font-normal-color\">");
      out.print(infeer_name);
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"excel_content dinylight-color font-normal-color\">");
      out.print(infeerID);
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"border_line\"></div>\r\n");
      out.write("\t\t");

			}
			}
		
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"tail_charge normal-color\">\r\n");
      out.write("\t\t<form name=\"form\" action=\"web_journal.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t<input value=\"");
      out.print(needsearch_content);
      out.write("\" name=\"needsearch_content\"\r\n");
      out.write("\t\t\t\tstyle=\"display: none;\" /> <input value=\"");
      out.print(needsearch_type);
      out.write("\"\r\n");
      out.write("\t\t\t\tname=\"needsearch_type\" style=\"display: none;\" /> <input\r\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(type);
      out.write("\" name=\"type\" style=\"display: none;\" />\r\n");
      out.write("\t\t\t<div class=\"jo_turnpage-conntrol\">\r\n");
      out.write("\t\t\t\t<div class=\"jo_turnpage-foin\">\r\n");
      out.write("\t\t\t\t\t<button value=\"1\" name=\"nowpage\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"jo_turnpage-number small-font font-normal-color\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 10%; cursor: pointer;\">\r\n");
      out.write("\t\t\t\t\t\t<font class=\"small-font\">首页</font>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<button value=\"");
      out.print(nowpage - 1);
      out.write("\" name=\"nowpage\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"cursor: pointer;\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"turnpage-number small-font font-normal-color\">\r\n");
      out.write("\t\t\t\t\t\t<font class=\"small-font\">上一页</font>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<div class=\"jo_turnpage-turn font-normal-color\">\r\n");
      out.write("\t\t\t\t\t\t<font class=\"small-font\">第");
      out.print(nowpage);
      out.write('页');
      out.write('/');
      out.write('共');
      out.print(allPages);
      out.write("页\r\n");
      out.write("\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"jo_turnpage-turn font-normal-color\" id=\"se\">\r\n");
      out.write("\t\t\t\t\t\t<select disabled=\"disabled\" name=\"nowpage\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"float: left; border: 0; margin-top: 9px; margin-left: 7%;\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"font-normal-color small-font\" id=\"check\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (int i = 1; i <= allPages; i++) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=");
      out.print(i);
      out.write(' ');
      out.print((nowpage == i) ? "selected" : "");
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t第");
      out.print(i);
      out.write("页\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"jo_turnpage-number small-font font-normal-color\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 20%; cursor: pointer;\">\r\n");
      out.write("\t\t\t\t\t\t\t<font class=\"small-font\">▶</font>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<button value=\"");
      out.print(nowpage + 1);
      out.write("\" name=\"nowpage\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"jo_turnpage-number small-font font-normal-color\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"cursor: pointer;\">\r\n");
      out.write("\t\t\t\t\t\t<font class=\"small-font\">下一页</font>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<button value=\"");
      out.print(allPages);
      out.write("\" name=\"nowpage\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"jo_turnpage-number small-font font-normal-color\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 10%; cursor: pointer;\">\r\n");
      out.write("\t\t\t\t\t\t<font class=\"small-font\">尾页</font>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
jt.con.close();
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
