/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2021-03-19 06:00:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Adminpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.journal_tool;

public final class web_005fjournal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.journal_tool");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<title>Insert title here</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write(".jo_turnpage-turn {\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tline-height: 35px;\r\n");
      out.write("\tfont-size: 28px;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin-left: 6px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tborder-radius: 6px;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".jo_turnpage-number {\r\n");
      out.write("\twidth: 15%;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tline-height: 30px;\r\n");
      out.write("\tfont-size: 28px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-left: 6px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tborder-radius: 6px;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".jo_turnpage-foin {\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\tmargin:0 auto;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\tmargin-top:5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".jo_turnpage-conntrol {\r\n");
      out.write("\tmargin-top: 1%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\theight: 45px;\r\n");
      out.write("}\r\n");
      out.write("\t.menu_dad{\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\twidth: 10%;\r\n");
      out.write("\t\theight: 823px;\r\n");
      out.write("\t\tmargin-left:1%;\r\n");
      out.write("\t\toverflow-y: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu_firstchild{\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 20px;\r\n");
      out.write("\t\tmargin-top: 20px;\r\n");
      out.write("\t\tbackground-color:  #FFA980;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu_child{\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 40px;\r\n");
      out.write("\t\tborder-bottom: 1px solid #fafafa;\r\n");
      out.write("\t\tmargin-top: 2px;\r\n");
      out.write("\t\tcolor: #FFA980;\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t\tfont-weight: 500;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tborder: 0;\r\n");
      out.write("\t\toutline: none;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tline-height: 40px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.display{\r\n");
      out.write("\t\theight: 823px;\r\n");
      out.write("\t\twidth: 88%;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tmargin-left: 1%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.body_charge{\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t\twidth: 90%;\r\n");
      out.write("\t\theight: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.head_charge{\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 70px;\r\n");
      out.write("\t\tmargin-top: 10px;\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t.stoma_charge{\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 630px;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tbackground-color: #FFE4D7;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tail_charge{\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 70px;\r\n");
      out.write("\t\tmargin-top: 10px;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t.search_block{\r\n");
      out.write("\t\twidth:50%;\r\n");
      out.write("\t\theight:400px;\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t\tcolor: #FFA980;\r\n");
      out.write("\t\tbackground-color:white;\r\n");
      out.write("\t\tmargin-top: 80px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.search_block button{\r\n");
      out.write("\t\toutline: none;\r\n");
      out.write("\t\tborder:0;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tbackground-color: #FFA980;\r\n");
      out.write("\t\twidth:70%;\r\n");
      out.write("\t\theight: 40px;\r\n");
      out.write("\t\tmargin-left:15%;\r\n");
      out.write("\t\tmargin-top: 40px;\r\n");
      out.write("\t\tborder-radius: 6px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.search_line{\r\n");
      out.write("\t\twidth: 70%;\r\n");
      out.write("\t\theight: 40px;\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t\tmargin-top: 20px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.search_line input{\r\n");
      out.write("\t\tmargin-top: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Admin_lead.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("block_id", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("8", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\t\t\r\n");

	request.setCharacterEncoding("UTF-8") ;//或者指定的编码(GBK或其他)
	String type="1";
	String needsearch_type = null;
	String needsearch_content = null;
	if(request.getParameter("type")!=null)
	{
		type=request.getParameter("type");
	}
	if(request.getParameter("needsearch_type")!=null)
	{
		needsearch_type =request.getParameter("needsearch_type");
	}
	if(request.getParameter("needsearch_content")!=null)
	{
		needsearch_content =request.getParameter("needsearch_content");
	}

      out.write("\r\n");
      out.write("\t\t<button class=\"menu_child\" style=\"display:none;\"></button>\r\n");
      out.write("\t\t<div style=\"width:87.5%;margin-left:0.1%;height:824px;float:left;\" class=\"dinylight-color\">\r\n");
      out.write("\t\t\t<div class=\"menu_dad\">\r\n");
      out.write("\t\t\t\t<form method=\"post\" action=\"web_journal.jsp\">\r\n");
      out.write("\t\t\t\t\t<div class=\"menu_firstchild\"></div>\r\n");
      out.write("\t\t\t\t\t<button class=\"menu_child\" value=\"1\" name=\"type\">全部日志\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<button class=\"menu_child\" value=\"2\" name=\"type\">条件查询\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<button class=\"menu_child\" value=\"3\" name=\"type\">特定人员\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<button class=\"menu_child\" value=\"4\" name=\"type\">特定时间\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<button class=\"menu_child\" value=\"5\" name=\"type\">特定行为\t\t\t\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<button class=\"menu_child\" value=\"6\" name=\"type\">受影响人\t\t\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<div class=\"display light-color\">\r\n");
      out.write("\t\t\t\t<div class=\"body_charge\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
if(type.equals("1")){
				
      out.write("\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "web_journal_child.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("type", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(type), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
if(type.equals("2")){
					if(needsearch_type==null){
      out.write("\r\n");
      out.write("\t\t\t\t\t<form action=\"web_journal.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"search_block\">\r\n");
      out.write("\t\t\t\t\t<div class=\"search_line\"><input name=\"needsearch_2_usename\"  placeholder=\"用户名\"/></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"search_line\"><input name=\"needsearch_2_useID\"  placeholder=\"用户ID\"/></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"search_line\"><input name=\"needsearch_2_cotent\" placeholder=\"用户行为\"/></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"search_line\"><input name=\"needsearch_2_begintime\" placeholder=\"开始时间\"/>- -<input name=\"needsearch_2_endtime\" placeholder=\"结束时间\"/></div>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"type\" value=\"2\"  style=\"display:none;\"/>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"needsearch_type\" value=\"needsearch_add\"  style=\"display:none;\"/>\r\n");
      out.write("\t\t\t\t\t\t<button>查询</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "web_journal_child.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("type", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(type), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("needsearch_type", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(needsearch_type), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("needsearch_content", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(needsearch_content), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\t\t\t\t");
}}
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
if(type.equals("3")){
					if(needsearch_type==null){
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<form action=\"web_journal.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div>根据用户名查询日志：<input name=\"needsearch_content\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"type\" value=\"3\"  style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"needsearch_type\" value=\"needsearch_username\"  style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<button>查询</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<form action=\"web_journal.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div>根据用户ID查询日志：<input name=\"needsearch_content\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"type\" value=\"3\"  style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"needsearch_type\" value=\"needsearch_userID\" style=\"display:none;\"> \r\n");
      out.write("\t\t\t\t\t\t\t<button>查询</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "web_journal_child.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("type", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(type), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("needsearch_type", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(needsearch_type), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("needsearch_content", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(needsearch_content), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t");
}}
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
if(type.equals("4")){//select * from journal where time>'2021-03-10' and time<'2021-03-11';
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>起始时间：<input type=\"date\" /></div>\r\n");
      out.write("\t\t\t\t\t<div>结束时间：<input type=\"date\"/></div>\r\n");
      out.write("\t\t\t\t\t<button>查询</button>\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
if(type.equals("5")){
					if(needsearch_type==null){
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<form action=\"web_journal.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div>根据行为查询日志：<input name=\"needsearch_content\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"type\" value=\"5\"  style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"needsearch_type\" value=\"needsearch_dowhat\"  style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<button>查询</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "web_journal_child.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("type", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(type), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("needsearch_type", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(needsearch_type), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("needsearch_content", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(needsearch_content), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t");
}}
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
if(type.equals("6")){
				if(needsearch_type==null){
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<form action=\"web_journal.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div>根据受影响人用户名查询日志：<input name=\"needsearch_content\"/>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"type\" value=\"6\"  style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"needsearch_type\" value=\"needsearch_innusername\"  style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<button>查询</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>根据受影响人ID查询日志：<input name=\"needsearch_content\"/>\r\n");
      out.write("\t\t\t\t\t\t<input name=\"type\" value=\"6\"  style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"needsearch_type\" value=\"needsearch_innuserID\"  style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<button>查询</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "web_journal_child.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("type", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(type), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("needsearch_type", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(needsearch_type), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("needsearch_content", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(needsearch_content), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\t\t\t\t");
}}
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script src=\"../js/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("\t$('.menu_child:eq(");
      out.print(type);
      out.write(")').addClass('light-color white-font');\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
